### ISSUE TITLE
feat: use conventional commits

### ISSUE THREAD

**Issue by oSumAtrIX** [BlueMoonDevelopment/ExpenseMan-API#18]
RE: https://www.conventionalcommits.org/en/v1.0.0/

Following a standard usually helps with consistency and allows integration of common CI/CD tools such as [semantic-release](https://github.com/semantic-release/semantic-release), further improving a streamlined development.

PS: Enable discussions for BlueMoonDevelopment where general discussions can be made.

**Comment by TheJeterLP** [comment]
> PS: Enable discussions for BlueMoonDevelopment where general discussions can be made.

Discussions are private right now. They might be open at a later stage.
Since the project is currently just beginning the focus is more on productivity rn than on conventional commits etc.
This will change later tho.
