### ISSUE TITLE
ToDo: Create data scheme

### ISSUE THREAD

**Issue by TheJeterLP** [BlueMoonDevelopment/expenseman-api#4]
Write down what data is exactly needed for the app to be stored so we can create the DB Scheme

**Comment by TheJeterLP** [comment]
- multiple accounts
- returning incomes
- returning expenses
- chart generation
- income / expense categories
- a way to store contract numbers for returning expenses like insurance numbers. (Possible desc field for ex)

**Comment by TigerCipher** [comment]
For expense category we need (at least):

- Purchase (i.e item, subscription service, whatever)
- Amount paid
- Boolean if its a recurring payment or not, and whether its monthly, 3 months, etc etc
- Description (Some people may want to record if it was for themself, a gift, work, etc)
- What bank account / card / cash / etc was used to pay

For income category, we need (at least):

- Amount received
- Sender
- Reason (salary, sold item, etc)
- Boolean if its recurring
- What bank account it was sent to

For accounts we need (at least):

- Bank name
- Optional details, like account number and such
- Balance

**Comment by TheJeterLP** [comment]
I think we shouldnt do recurring categories, but recurring payments. Like do one Table for standard payments and one for recurring ones

**Comment by TigerCipher** [comment]
Yeah I'd agree with that. We can make it optional but I do think we should have categories or something similar. Like for me, I'd like to easily navigate to streaming subscriptions (netflix, prime, hulu, etc), game subscriptions (swtor, WoW, etc), bills, etc

**Comment by TheJeterLP** [comment]
oh yea definitely catergories is a must to add. But it should be optional yea. So we should Basically link the accounts to the userid and the categories to the userid. All the expenses and incomes should then be linked to the accountid.

Just so we can do for example:
GET ALL accounts from user userid
GET ALL incomes for account accountid

and obviously check if the accounts belong to the user first. So they must be authenticated with the token in order to see their own data

**Comment by TigerCipher** [comment]
Yeah. And then from that, things like `GET ALL expenses for account accountid` and such, yeah?

**Comment by TheJeterLP** [comment]
yes exactly

**Comment by TheJeterLP** [comment]
and then just server all the data as JSON response like we already do in the API
